"""Build percentile pools and accept curves from OUR OWN live games.

Why this exists
---------------
`build_targets.py` compiles the public GLEE research dataset, which was
generated by 2024-vintage models. Measured against our own logs that answer
key is badly miscalibrated for the live field:

  * the dataset bargaining accept curve is 2-4x optimistic (give=0.25 priced
    at 14.8% vs 3.7% realized live);
  * half of our bargaining games match no dataset pool at all;
  * live negotiation percentiles imply ~0.50 where the dataset says ~0.81.

Every accept/offer rule we have is tuned against that key, so correcting it
moves all three families at once.

Two de-biasing choices matter. First, pools are built from the OPPONENT's
payoffs as well as ours: the opponent sample is the field, uncontaminated by
our own policy, and it doubles the sample. Second, a live cell only
overrides the dataset cell once it has MIN_N observations; below that the
dataset prior stands.

Output schema is identical to data/targets.json so `theory/targets.py` can
merge the two without any strategy code changing.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from glee_agent.theory import targets as T  # noqa: E402

DB = Path(__file__).resolve().parents[1] / "data" / "agent.db"
OUT = Path(__file__).resolve().parents[1] / "data" / "live_targets.json"
GRID = [round(0.05 * i, 2) for i in range(1, 20)]   # q05 .. q95
MIN_N = 40          # a live cell needs this many payoffs to override the prior
MIN_BUCKET_N = 30   # an accept-curve bucket needs this many observations


def quantiles(vals: list[float]) -> list[float]:
    vals = sorted(vals)
    if not vals:
        return []
    out = []
    for q in GRID:
        idx = q * (len(vals) - 1)
        lo, hi = int(idx), min(int(idx) + 1, len(vals) - 1)
        frac = idx - lo
        out.append(round(vals[lo] * (1 - frac) + vals[hi] * frac, 6))
    return out


def other(role: str) -> str:
    return "player_2" if role == "player_1" else "player_1"


def build_accept_curves(con, neg_state) -> tuple[dict, dict]:
    """P(opponent accepts | what we offered them), measured on the live field.

    This is the half of the answer key that matters most: the optimizers in
    both families pick an offer by maximising `payoff x P(accept)`, and the
    dataset curve is 2-4x optimistic here (a bargaining give of 0.25 is
    priced at 14.8% by the dataset and realizes 3.7% live). Standalone offer
    turns are already stamped with their offer round. Negotiation counters
    are emitted by a RejectOffer decision and become the following round's
    offer. In either case an offer is accepted only when the game's agreement
    is stamped with that normalized offer round.
    """
    games = {}
    for r in con.execute(
        "SELECT game_id, family, outcome, agreed_round, config_json, opp_type "
        "FROM games WHERE config_json IS NOT NULL"
    ):
        games[(r["game_id"], r["family"])] = r

    barg = defaultdict(lambda: [0, 0])
    neg = defaultdict(lambda: [0, 0])

    for r in con.execute(
        "SELECT game_id, family, your_player, round, action_json, action_type, opp_type "
        "FROM turns WHERE action_json IS NOT NULL AND family IN ('bargaining','negotiation')"
    ):
        g = games.get((r["game_id"], r["family"]))
        if g is None:
            continue
        try:
            act = json.loads(r["action_json"])
            cfg = json.loads(g["config_json"])
        except Exception:
            continue
        try:
            turn_round = int(r["round"])
        except (TypeError, ValueError):
            continue
        if r["action_type"] == "offer":
            offer_round = turn_round
        elif (r["family"] == "negotiation"
              and act.get("decision") == "RejectOffer"):
            # The counter is made during round r's decision but is recorded
            # by the platform as the offer for round r + 1.
            offer_round = turn_round + 1
        else:
            # Accept/reject/walk-away decisions are outcomes of someone
            # else's offer, not additional offer observations of our own.
            continue
        accepted = int(g["outcome"] == "agreement"
                       and (g["agreed_round"] or -1) == offer_round)
        human = (r["opp_type"] or g["opp_type"]) == "human"
        max_rounds = cfg.get("max_rounds")
        left = (None if max_rounds is None
                else int(max_rounds) - offer_round + 1)
        rl = T._rounds_left_bucket(left)

        if r["family"] == "bargaining":
            money = float(cfg.get("money_to_divide") or 0)
            if money <= 0:
                continue
            idx = 1 if r["your_player"] == "player_1" else 2
            mine = act.get(f"player_{idx}_gain", act.get({1: "alice_gain", 2: "bob_gain"}[idx]))
            if not isinstance(mine, (int, float)):
                continue
            to_them = 1.0 - float(mine) / money
            key = T._dumps({"share_bucket": T._bucket_005(to_them, 0.0, 0.95),
                            "rounds_left_bucket": rl, "human": bool(human)})
            cell = barg[key]
        else:
            price = act.get("product_price")
            if not isinstance(price, (int, float)):
                continue
            st = neg_state.get(r["game_id"])
            if st is None:
                continue
            me = r["your_player"] or "player_1"
            opp = "player_2" if me == "player_1" else "player_1"
            their_role = st.get(f"{opp}_role")
            their_value = st.get(f"{opp}_value")
            if their_role not in ("seller", "buyer") or not their_value:
                continue
            rel = float(price) / float(their_value)
            key = T._dumps({"rel_bucket": T._bucket_005(rel, 0.0, 1.95),
                            "role": their_role, "rounds_left_bucket": rl,
                            "human": bool(human)})
            cell = neg[key]
        cell[0] += 1
        cell[1] += accepted

    barg_out = {k: v for k, v in barg.items() if v[0] >= MIN_BUCKET_N}
    neg_out = {k: v for k, v in neg.items() if v[0] >= MIN_BUCKET_N}
    print(f"accept curves: bargaining {len(barg_out)} buckets, "
          f"negotiation {len(neg_out)} buckets", flush=True)
    return barg_out, neg_out


def build_payoff_pools(con, neg_state) -> tuple[dict, dict]:
    """Collect exact and visible-information-marginal live payoff pools.

    Exact keys are shared by both seats, so the opponent payoff remains a
    useful field sample there.  Marginal keys are role-specific: adding the
    opponent payoff would assign it to a key built from *our* visible value
    and contaminate the pool, so those cells receive only ``my_payoff``.
    """
    pools: dict[str, dict[str, dict[str, list[float]]]] = {
        f: defaultdict(lambda: defaultdict(list)) for f in
        ("bargaining", "negotiation", "persuasion")
    }
    n_games = defaultdict(int)

    for r in con.execute(
        "SELECT game_id, family, your_player, config_json, my_payoff, opp_payoff "
        "FROM games WHERE config_json IS NOT NULL AND my_payoff IS NOT NULL"
    ):
        fam = r["family"]
        if fam not in pools:
            continue
        try:
            cfg = json.loads(r["config_json"])
        except Exception:
            continue
        role = r["your_player"] or "player_1"
        entries: list[tuple[str, bool]] = []  # (key, role-specific marginal)
        if fam == "bargaining":
            exact = T.config_key_bargaining(cfg)
            marginal = T.config_key_bargaining_marginal(cfg, role)
            if exact is not None:
                entries.append((exact, False))
            if marginal is not None:
                entries.append((marginal, True))
        elif fam == "persuasion":
            exact = T.config_key_persuasion(cfg)
            marginal = T.config_key_persuasion_marginal(cfg, role)
            if exact is not None:
                entries.append((exact, False))
            if marginal is not None:
                entries.append((marginal, True))
        else:
            st = neg_state.get(r["game_id"])
            if st is None:
                continue
            my_role = st.get(f"{role}_role") or (
                "seller" if role == "player_1" else "buyer"
            )
            full, rolekey = T.config_key_negotiation(
                st, my_role, st.get(f"{role}_value")
            )
            if full is not None:
                entries.append((full, False))
            elif rolekey is not None:
                entries.append((rolekey, True))
        if not entries:
            continue

        n_games[fam] += 1
        for key, role_specific in entries:
            pools[fam][key][role].append(float(r["my_payoff"]))
            if r["opp_payoff"] is not None and not role_specific:
                pools[fam][key][other(role)].append(float(r["opp_payoff"]))

    return pools, n_games


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=str(DB))
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    con = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row

    # Negotiation's config key needs player_N_role, which lives in the live
    # game_state rather than in the stored config: recover one state per game.
    neg_state: dict[str, dict] = {}
    for r in con.execute(
        "SELECT game_id, state_json FROM turns "
        "WHERE family='negotiation' AND state_json IS NOT NULL"
    ):
        try:
            neg_state[r["game_id"]] = json.loads(r["state_json"])
        except Exception:
            continue
    print(f"recovered negotiation state for {len(neg_state)} games", flush=True)

    pools, n_games = build_payoff_pools(con, neg_state)

    out: dict = {
        "built_from": "live",
        "n_games": {k: v for k, v in n_games.items()},
        "quantile_grid": GRID,
        "min_n": MIN_N,
    }
    for fam, cells in pools.items():
        emitted = {}
        for key, byrole in cells.items():
            rec = {"n": sum(len(v) for v in byrole.values()), "payoff_q": {}}
            for role, vals in byrole.items():
                if len(vals) >= MIN_N:
                    rec["payoff_q"][role] = quantiles(vals)
            if rec["payoff_q"]:
                emitted[key] = rec
        out[fam] = emitted
        print(f"{fam}: {len(emitted)} live cells from {n_games[fam]} games", flush=True)

    out["barg_accept"], out["neg_accept"] = build_accept_curves(con, neg_state)

    Path(args.out).write_text(json.dumps(out))
    print(f"wrote {args.out} ({Path(args.out).stat().st_size/1e6:.2f} MB)")


if __name__ == "__main__":
    main()
